#############################################################################
# Makefile for building: QT_demo_App
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  QT_demo_App.pro
# Template: app
# Command: /opt/poky/daisy/sysroots/i686-pokysdk-linux/usr/bin/qt5/qmake -o Makefile QT_demo_App.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = $(OE_QMAKE_CC)
CXX           = $(OE_QMAKE_CXX)
DEFINES       = -DQT_NO_DEBUG -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe $(OE_QMAKE_CFLAGS) -O2 -DLINUX=1 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe $(OE_QMAKE_CXXFLAGS) -O2 -DLINUX=1 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++ -I. -I. -I/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5 -I/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtQml -I/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtNetwork -I/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtGui -I/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore -I. -I/home/balakrishnan/userFSLimx6YoctoBuildDir/fsl-release-bsp/build-x11/tmp/sysroots/imx6solosabresd/usr/include/libdrm
LINK          = $(OE_QMAKE_LINK)
LFLAGS        = $(OE_QMAKE_LDFLAGS) -Wl,-O1
LIBS          = $(SUBLIBS) -L/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib -lQt5Qml -lQt5Network -lQt5Gui -lQt5Core -lGLESv2 -lEGL -lGAL -lpthread 
AR            = $(OE_QMAKE_AR) cqs
RANLIB        = 
QMAKE         = /opt/poky/daisy/sysroots/i686-pokysdk-linux/usr/bin/qt5/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = $(OE_QMAKE_STRIP)
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_qml.cpp
OBJECTS       = main.o \
		qrc_qml.o
DIST          = /opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/shell-unix.conf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/unix.conf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/linux.conf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/qconfig.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3d.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3d_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_compositor.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_compositor_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_post.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_post.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/resources.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/moc.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/yacc.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/lex.prf \
		QT_demo_App.pro \
		qml.qrc \
		QT_demo_App.pro
QMAKE_TARGET  = QT_demo_App
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = QT_demo_App


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QT_demo_App.pro /opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf /opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/shell-unix.conf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/unix.conf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/linux.conf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/qconfig.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3d.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3d_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_compositor.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_compositor_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_post.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_post.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/resources.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/moc.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/yacc.prf \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/lex.prf \
		QT_demo_App.pro \
		qml.qrc \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/libQt5Qml.prl \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/libQt5Network.prl \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/libQt5Core.prl \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/libQt5Gui.prl
	$(QMAKE) -o Makefile QT_demo_App.pro
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_pre.prf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/shell-unix.conf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/unix.conf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/linux.conf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base.conf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-base.conf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-unix.conf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/qconfig.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3d.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3d_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_compositor.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_compositor_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_declarative.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webkit.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_functions.prf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_config.prf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_post.prf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/exclusive_builds.prf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_pre.prf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/resolve_config.prf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_post.prf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/warn_on.prf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt.prf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/resources.prf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/moc.prf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/opengl.prf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/thread.prf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/testcase_targets.prf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/exceptions.prf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/yacc.prf:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/features/lex.prf:
QT_demo_App.pro:
qml.qrc:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/libQt5Qml.prl:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/libQt5Network.prl:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/libQt5Core.prl:
/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/libQt5Gui.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile QT_demo_App.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/QT_demo_App1.0.0 || mkdir -p .tmp/QT_demo_App1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QT_demo_App1.0.0/ && $(COPY_FILE) --parents qml.qrc .tmp/QT_demo_App1.0.0/ && $(COPY_FILE) --parents main.cpp .tmp/QT_demo_App1.0.0/ && (cd `dirname .tmp/QT_demo_App1.0.0` && $(TAR) QT_demo_App1.0.0.tar QT_demo_App1.0.0 && $(COMPRESS) QT_demo_App1.0.0.tar) && $(MOVE) `dirname .tmp/QT_demo_App1.0.0`/QT_demo_App1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QT_demo_App1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		rpm_red_glow.png \
		Sports_inner_ring.png \
		FG_glow_left.png \
		sport_numbers.png \
		Center_Large_2.png \
		Park_Brake.png \
		Top_Bar.png \
		Seat_Belt.png \
		Headlamp.png \
		Sports.qml \
		Tacho_glow.png \
		Center_White.png \
		Start_msg.png \
		Sport_Mode_ring.png \
		MIL.png \
		FG_glow_R.png \
		Blue_arc.png \
		TG_graphics.png \
		Right_Ring.png \
		Welcome_Text.png \
		Sport_text.png \
		ABS.png \
		speedometer.qml \
		FG_grad_left.png \
		Speedo_text.png \
		Sports_graduation.png \
		PS_Failure.png \
		Cruise_control.png \
		FG_fil_left.png \
		Bottom_Bar.png \
		Left_Ring.png \
		right_turn.png \
		Tacho_text.png \
		Sport_text_movement.png \
		main.qml \
		centre_black.png \
		FG_graduations_R.png \
		speedo_glow.png \
		TG.png \
		Battery.png \
		FG_graphics.png \
		FG_filling_R.png \
		Sports_Bottom.png \
		Sports_red_TG.png \
		HI_beam.png \
		Center_Large_3.png \
		FG.png \
		FG_inside.png \
		left_turn.png \
		Pricol_logo.png \
		Sports_red_FG.png \
		Sports_topbar.png \
		Sport_lines.png \
		Center_Pink.png \
		Final_pointer.png \
		Airbag.png
	/opt/poky/daisy/sysroots/i686-pokysdk-linux/usr/bin/qt5/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean 

####### Compile

main.o: main.cpp /opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/QGuiApplication \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qguiapplication.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qcoreapplication.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qglobal.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qconfig.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qfeatures.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qsystemdetection.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qprocessordetection.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qcompilerdetection.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qglobalstatic.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qbasicatomic.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qgenericatomic.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_msvc.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_integrity.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_power.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_alpha.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv7.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv6.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv5.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_bfin.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_ia64.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_mips.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_s390.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_sparc.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_x86.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_gcc.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_unix.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qmutex.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qlogging.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qflags.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qtypeinfo.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qtypetraits.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qsysinfo.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qstring.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qchar.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qbytearray.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qrefcount.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qnamespace.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qarraydata.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qstringbuilder.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qobject.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qobjectdefs.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qlist.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qalgorithms.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qiterator.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qcoreevent.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qscopedpointer.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qmetatype.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qvarlengtharray.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qcontainerfwd.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qisenum.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qobject_impl.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qeventloop.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qwindowdefs.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qinputmethod.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qlocale.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qvariant.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qmap.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qpair.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qdebug.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qhash.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qtextstream.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qiodevice.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qvector.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qpoint.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qset.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qcontiguouscache.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qstringlist.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qdatastream.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qregexp.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qstringmatcher.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qshareddata.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qsize.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtQml/QQmlApplicationEngine \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtQml/qqmlapplicationengine.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtQml/qqmlengine.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qurl.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qurlquery.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtQml/qjsengine.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qsharedpointer.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtQml/qjsvalue.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtQml/qtqmlglobal.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtQml/qqmlerror.h \
		/opt/poky/daisy/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5/QtQml/qqmldebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

