######################################################################
# Automatically generated by qmake (3.0) Sun Nov 22 02:39:33 2015
######################################################################
QT += qml
TEMPLATE = app
TARGET = QT_demo_App
INCLUDEPATH += .

# Input
SOURCES += main.cpp
RESOURCES += qml.qrc
